- name: Slack Notification
  uses: tokorom/action-slack-incoming-webhook@main
  env:
    INCOMING_WEBHOOK_URL: ${{ https://hooks.slack.com/services/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 }}
  with:
    text: Hello, Slack!
